apiVersion: servicemesh.cisco.com/v1alpha1
kind: IstioMeshGateway
metadata:
  annotations:
    banzaicloud.io/related-to: istio-system/cp-v112x
  labels:
    app: nginx-service
    istio.io/rev: cp-v112x.istio-system
  name: nginx-ingressgateway
spec:
  deployment:
    podMetadata:
      labels:
        app: nginx-service
        istio: ingressgateway
  istioControlPlane:
    name: cp-v112x
    namespace: istio-system
  service:
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 80
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443
    type: LoadBalancer
  type: ingress
