kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-1
nodes:
- role: control-plane
  image: kindest/node:v1.23.6
- role: worker
  image: kindest/node:v1.23.6
- role: worker
  image: kindest/node:v1.23.6