apiVersion: smm.cisco.com/v1alpha1
kind: IstioOperator
metadata:
  annotations:
    banzaicloud.io/managed-component: smm-mesh-manager-smm.cisco.com/v1alpha1-controlplane
    banzaicloud.io/related-to: /smm
  name: v115x
  namespace: smm-system
spec:
  enabled: true
  image:
    pullPolicy: Always
    repository: docker.io/nishantapatil3/istio-operator
    tag: v2.15.7
  imagePullSecrets:
  - name: smm-pull-secret
  namespace: smm-system
  prometheusMetrics:
    authProxy:
      image:
        pullPolicy: IfNotPresent
        repository: quay.io/brancz/kube-rbac-proxy
        tag: v0.11.0
  version: 1.15.3
