apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    successCondition: result[0] >= 95
    interval: 30s
    failureLimit: 5
    provider:
      prometheus:
        address: http://prometheus.istio-system.svc.cluster.local:9090
        query: |
          100 * sum(rate(istio_requests_total{reporter="source",destination_service="rollouts-demo-canary.default.svc.cluster.local",response_code!~"5.*"}[1m]))
          /
          sum(rate(istio_requests_total{reporter="source",destination_service="rollouts-demo-canary.default.svc.cluster.local"}[1m]))
