apiVersion: servicemesh.cisco.com/v1alpha1
kind: IstioMeshGateway
metadata:
  annotations:
    banzaicloud.io/related-to: istio-system/cp-v113x
  labels:
    app: test-imgw-app
    istio.io/rev: cp-v113x.istio-system
  name: test-imgw
  namespace: test
spec:
  deployment:
    podMetadata:
      labels:
        app: test-imgw-app
        istio: ingressgateway
  istioControlPlane:
    name: cp-v113x
    namespace: istio-system
  service:
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 8080
    type: LoadBalancer
  type: ingress
